# main configuration file
# Format is self-explanatory. Do not use quotes around multi-word values
[hardware]
# The specific AVR chip variant
CHIP_VARIANT = ATMEGA1284p
# available program storage space for compiled code, in bytes
MAXIMUM_SIZE = 130048
# available dynamic memory for global variables, in bytes
RAM_SIZE = 16384
# CPU clock speed in Hz
F_CPU = 8000000L
# The upload speed in bits per second for AVRDude
UPLOAD_SPEED = 57600

[names]
# machine-friendly board name, used as directory name in filesystem
# all lower case, no spaces or special characters except underscores
# NOTE: You MUST have a unique BOARD_NAME for each board variant and hardware version!
BOARD_NAME = mayfly2
# Board version; intended for hardware versions where a very similar board has slightly different pin arrangements across versions.
BOARD_VERSION = 2.0.0
# Human-readable board name
# This should be unique for each board variant and hardware version
BOARD_NAME_LONG = EnviroDIY Mayfly v2
# DEFINE_NAME is used to set a compile-time macro ARDUINO_DEFINE_NAME
# if you leave this blank, the board name will be used, but converted to upper case and with non-alphanumeric characters replaced by underscores
# NOTE: This does not need to be unique for each hardware version.
# The version number is set as a separate define.
BOARD_DEFINE_NAME = AVR_ENVIRODIY_MAYFLY

[additional_build_flags]
# Experts only.
# -D__{chip_variant}__ is always added
# If you have any additional GCC build flags that you want to add, put them here as space-separated list
EXTRA_EXTRA_FLAGS = -DSD_CHIP_SELECT_MODE=1
# "-DVARIANT_QSPI_BAUD_DEFAULT=50000000"

# For SdFat, defining SD_CHIP_SELECT_MODE as 1 allow overwriting the functions to set the pin mode and level for the SS (slave/chip) select mode
# Chip select mode 1 allows you to write your own functions without requiring it.
# By default, SdFat initializes the SS pin by setting pin mode to OUTPUT,
# prepares to write by setting the SS pin to LOW,
# and finishes communication by setting the SS pin to HIGH.
# ```cpp
# void sdCsInit(SdCsPin_t pin) {
#   initCalls++;
#   pinMode(pin, OUTPUT);
# }
# void sdCsWrite(SdCsPin_t pin, bool level) {
#   writeCalls++;
#   digitalWrite(pin, level);
# }

# cSpell:words ifdefs myboard MSSEN DVARIANT DENABLE DARM DARDUINO DENVIRODIY MFLOAT MFPU POWERPIN PULLUP GCLK PINMUX UART
