# main configuration file
# Format is self-explanatory. Do not use quotes around multi-word values
[vendor]
# Vendor name. Short version, no spaces, lower case, e.g. island_robotics
VENDOR_NAME = envirodiy
# Full, human-readable vendor name, e.g. Island Robotics LLC
VENDOR_NAME_LONG = EnviroDIY
# Main webpage for your project. Among other things, used for
# "More info" link in Arduino board manager
INFO_URL = https://www.envirodiy.org/
# used for "online help" link in Arduino board manager. Should
# be a link to support forum if you have one; otherwise, just copy
# INFO_URL
HELP_URL = https://www.envirodiy.org/help/
MAINTAINER_NAME = Stroud Water Research Center - EnviroDIY
VENDOR_EMAIL = info@envirodiy.org

[package]
# name to use for your custom board support package, e.g.
# My New SAMD Board
# will be used by Board menu of Arduino IDE
PACKAGE_NAME = EnviroDIY ATmega Boards
# Package version
PACKAGE_VERSION = 2.1.0
# Package base url - will have the zip archive name appended to it
PACKAGE_URL = https://github.com/EnviroDIY/Arduino_boards/raw/master/EnviroDIYAVRBoards/
# URL to the json file with the package index, used for Arduino board manager
# Fill this out if you want to update an existing package based on a downloadable JSON file
# If you are creating a new package, comment this out
PACKAGE_INDEX_URL = https://raw.githubusercontent.com/EnviroDIY/Arduino_boards/refs/heads/master/package_EnviroDIY_index.json
# Location of a local json file with the package index, used for Arduino board manager
# Fill this out if you want to update an existing package based on a local JSON file
# If you are creating a new package, comment this out
PACKAGE_INDEX_FILE = C:/Users/sdamiano/Documents/GitHub/EnviroDIY/Arduino_boards/package_envirodiy_index.json
# DEFINE_NAME is used to set a compile-time macro with the package version, which can be used in your code to check for package version
# if you leave this blank, the package name will be used, but converted to upper case and with non-alphanumeric characters replaced by underscores
PACKAGE_DEFINE_NAME = ENVIRODIY_ATMEGA_BOARDS

# cSpell:words ifdefs myboard MSSEN DVARIANT DENABLE DARM DARDUINO DENVIRODIY MFLOAT MFPU POWERPIN PULLUP GCLK PINMUX UART
